version: '3.8'

services:
  app:
    build: .
    container_name: gotika-back-app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    container_name: gotika-redis
    ports:
      - "6379:6379"

  db:
    image: postgres:17
    container_name: gotika-postgres
    ports:
      - "5432:5432"