spring:
  application:
    name: gotika-backend
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/gotikaDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  #    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
  security:
    user:
      password: yeat
  mail:
    host: smtp.mail.ru
    port: 587
    username: gotika.no-reply@mail.ru
    password: vfz82icvRUBzuYNXm8y8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.mail.ru
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: EJRNGJKERNHTRHNUI32895734GERGERGERG6BIJ36BNJKL4537I38KJB86HJ34B8HJ3B65JH8B3K8B3KJ8B
  accessToken:
    expiration: 900000
    cookie-name: access
  refreshToken:
    expiration: 604800000
    cookie-name: refresh

cloudinary:
  url: cloudinary://171927165332578:6tqUCnBWHM6s7e3H0IivtgzV6O8@dsx6e6phm

yookassa:
  shop-id: 999174
  secret-key: test_6GJwionocOkNcVs9kXmfSdW63Pd6VyRc9_VDmDL_2Ko
  api-url: https://api.yookassa.ru/v3/payments
