spring:
  application:
    name: gotika-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/gotikaDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
  security:
    user:
      password: yeat
  mail:
    host: smtp.mail.ru
    port: 587
    username: gotika.no-reply@mail.ru
    password: vfz82icvRUBzuYNXm8y8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.mail.ru
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${SECRET_KEY}
  accessToken:
    expiration: 900000
    cookie-name: access
  refreshToken:
    expiration: 604800000
    cookie-name: refresh

cloudinary:
  url: ${CLOUDINARY_URL}

yookassa:
  shop-id: 999174
  secret-key: ${YOOKASSA_SECRET_KEY}
  api-url: https://api.yookassa.ru/v3/payments