spring:
  application:
    name: gotika-backend
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  #    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
  security:
    user:
      password: ${SECURITY_PASSWORD}
  mail:
    host: smtp.mail.ru
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.mail.ru
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET_KEY}
  accessToken:
    expiration: 900000
  refreshToken:
    expiration: 604800000
cloudinary:
  url: ${CLOUDINARY_URL}

yookassa:
  shop-id: ${YOOKASSA_SHOP_ID}
  secret-key: ${YOOKASSA_SECRET_KEY}
  api-url: https://api.yookassa.ru/v3/payments
